### ISSUE TITLE
Make fields accessible by __getitem__

### ISSUE THREAD

**Issue by Allan-S-Menefee** [M0r13n/pyais#23]
I'm working with pyais and I'm finding the syntax NMEAMessage(blah).asdict()['mmsi']) clumsy. It should be possible to subscript these fields if NMEAMessage defined a __getitem__.

I will try to enter a pull request at some point, if I'm able to make time.

**Comment by M0r13n** [comment]
Hey, 

jep, you are definitely right. I believe that I tried it during the early days of Pyais. Back then I came across some kind of issue/error and stopped working on it. Anyway I would love to see a PR from you. Otherwise I will try to implement it, as soon as time allows!


Kind regards, 
Leon

**Comment by M0r13n** [comment]
Hey,

I made the `NMEAMessage` class subscriptable. You can now access it's fields via `[]`. See: https://pyais.readthedocs.io/en/latest/messages.html


Please note, that you provided `NMEAMessage(blah).asdict()['mmsi'])` as an example. This still won't work, because the `NMEAMessage` just capsules the NMEA message. It does not know or care about the actual payload. In order to access the `mmsi`, you first have to call `NMEAMessage.decode()`.
