### ISSUE TITLE
Exception when trying to decode multipart payloads

### ISSUE THREAD

**Issue by grndng** [M0r13n/pyais#37]
When trying to decode messages with the `decode_msg` function, I run into the exception that the message is not currently supported (in the file _decode.py_). I've checked out the file but don't understand what the problem is. One AIS payload that was encoded correctly looks as following:
```
AIS:
 !AIVDM,1,1,,B,34SNn:50000eUKHN`Ai0a41d0DU:,0*40
Decoded:
 {'type': 3, 'repeat': 0, 'mmsi': '305641000', 'status': <NavigationStatus.Moored: 5>, 'turn': 0, 'speed': 0.0, 'accuracy': 0, 'lon': 9.958153333333334, 'lat': 53.52864666666667, 'course': 16.400000000000002, 'heading': 128, 'second': 54, 'maneuver': <ManeuverIndicator.NotAvailable: 0>, 'raim': 0, 'radio': 84298}
```

and it works right until I run into a message with `!AIVDM,2`:
```
!AIVDM,2,1,0,A,539p4OT00000@7W3K@08ThiLE8@E:0000000001S0h9135Pl?0R0C@UDQp00,0*68
{'type': 5, 'repeat': 0, 'mmsi': '211682430', 'ais_version': 1, 'imo': 0, 'callsign': 'DA9064', 'shipname': 'BILLWERDER', 'shiptype': <ShipType.OtherType_NoAdditionalInformation: 99>, 'to_bow': 6, 'to_stern': 9, 'to_port': 1, 'to_starboard': 3, 'epfd': <EpfdType.GPS: 1>, 'month': 6, 'day': 1, 'hour': 20, 'minute': 15, 'draught': 0.2, 'destination': 'HAMBURG', 'dte': 0}
!AIVDM,2,2,0,A,00000000000,2*24
pyais.exceptions.UnknownMessageException: The message b'!AIVDM,2,2,0,A,00000000000,2*24' is not currently supported!
```

Is multipart payload decoding not supported yet or am I not understanding what exactly to do when I encounter a multipart payload?

**Comment by M0r13n** [comment]
The error message that you get is misleading. Trying to decode a multipart message without its predecessor will yield this error, because the payload can not be decoded properly. 

In the [documentation]((https://pyais.readthedocs.io/en/latest/examples/single.html#examples)) I point out that `decode_msg` is only a convenience function for quick experimenting/testing. It is designed to decode a single message. However, it can be used to decode multipart messages, **if you provide all parts**:

```py
decode_msg(
    "!AIVDM,2,1,0,A,539p4OT00000@7W3K@08ThiLE8@E:0000000001S0h9135Pl?0R0C@UDQp00,0*68",
    "!AIVDM,2,2,0,A,00000000000,2*24"
)
```

Depending on your use case, there are more stable methods to decode messages. Some examples:

1. Decoding messages from a file

```py
from pyais.stream import FileReaderStream

for msg in FileReaderStream("sample.ais"):
    decoded_message = msg.decode()
```

2. Reading from a socket

```py
from pyais.stream import TCPStream

url = 'ais.exploratorium.edu'
port = 80

for msg in TCPStream(url, port=80):
    decoded_message = msg.decode()
    ais_content = decoded_message.content
    print(ais_content)
    # Do something with the ais message
```

In both cases, the library will handle multipart messages for you. It will also handle out of order message decoding, which can happen when receiving messages via UDP.

**Comment by M0r13n** [comment]
I added more useful error messages: https://github.com/M0r13n/pyais/pull/38
