### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_json'

### ISSUE THREAD

**Issue by void4main** [M0r13n/pyais#4]
Hi,

I have this:

```
msg = b'!AIVDM,1,1,,B,0S9edj0P03PecbBN`ja@0?w42cFC,0*7C'
msg = NMEAMessage(msg)
```

which returns

`None`

so if I pass this directly to convert it to json

`message = msg.decode().to_json()
`
I get:

Traceback (most recent call last):
  File "./get3.py", line 33, in <module>
    message = msg.decode().to_json()
AttributeError: 'NoneType' object has no attribute 'to_json'

to_json can't handle these types, might be a good feature for new minor release :-)

Best,
Frank

**Comment by M0r13n** [comment]
Hey,

thanks again for the bug report!

This message itself is weird. I have never seen a type zero message. I also cound find any information regarding type zero messages. But they seem to be the same as type 1,2,3. I decided to add support them with the next release. This message has it's own testcase: https://github.com/M0r13n/pyais/blob/74df08e47ff0012d9fb771f66385526efc1e410f/tests/test_ais.py#L118


Regarding your general issue: Yes it is true, that some messages return None. This happens if my decoder encounters an unexpected issue. By default it will just return None and continue silently. I would recommend that you do a check for `None`, before you try to convert it into json.

**Comment by void4main** [comment]
Thanks,

I have one more b'!AIVDM,1,1,,B,139fgIPP00Pe,0*63'
Probably some cheap device or for testing purposes.
Since the type 0 are not defined it might be better to not process them, maybe you can log them if some debuglevel is set.

When I check whether it is None, I cannot use message = msg.decode().to_json() anymore? That would be sad.
Maybe I'll find a way and send a pull request for a new to_json :-)

Frank

**Comment by M0r13n** [comment]
Well, if you really want to keep using this onliner, you could do this:

```py
try:
    msg.decode().to_json()
    # so something 
except AttributeError:
    # handle error
```

**Comment by void4main** [comment]
That's good, thanks!

**Comment by M0r13n** [comment]
I included the bugfix in the newest release. Feel free to upgrade and tell me how it works for you! 😎

**Comment by void4main** [comment]
Like it, let's see 👍
