### ISSUE TITLE
Is ROT(Turn) decoding properly?

### ISSUE THREAD

**Issue by bgercken** [M0r13n/pyais#73]
Hello,

I am seeing a lot of sentences where the value for "turn" is being set to None, which is causing them to equal `<null>` when I store them. Using some of the lines from your decode.py example:

```
import pyais as pa
from pyais import decode

print('version: ', end='')
print(pa.__version__)

# Decode a single part using decode
decoded = decode(b"!AIVDM,1,1,,B,15NG6V0P01G?cFhE`R2IU?wn28R>,0*05")
print(decoded)

# Added my sentence for example 2
decoded = decode("!AIVDM,1,1,,B,15Nfbk3P00rq:4`Gkga7MwvP2L0L,0*0D")
print(decoded)
```

For both sentence we gate a value of **None** for turn:

```
version: 2.1.2
MessageType1(msg_type=1, repeat=0, mmsi=367380120, status=<NavigationStatus.UnderWayUsingEngine: 0>, turn=None, speed=0.1, accuracy=False, lon=-122.404333, lat=37.806948, course=245.2, heading=511, second=59, maneuver=0, spare_1=b'\x00', raim=True, radio=34958)
MessageType1(msg_type=1, repeat=0, mmsi=367766220, status=<NavigationStatus.RestrictedManoeuverability: 3>, turn=None, speed=0.0, accuracy=True, lon=-71.39986, lat=41.60838, course=191.1, heading=511, second=16, maneuver=0, spare_1=b'\x00', raim=True, radio=114716)
```

From an online decoder (http://ais.tbsalling.dk/) using the same sentence(s) we get a value of no turn information available:

```
rateOfTurn | -128
```

When I decode and store these values as a float they are being set to `<null>`. I am confused as to how the from_converter and to_converter are working. Can you please explain? Is the bit field just not receiving the right data?

Thanks.
-bill

```
print(sys.version)
3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
```

**Comment by bgercken** [comment]
Closing this issue as it is a non-issue. I made a local copy and adjusted the code to return a value rather than None for the -127/-128 use case. The change is specific to the work that I am doing. Thanks.

**Comment by bgercken** [comment]
Now I have a new question to consider. It appears that you may be rounding the product before squaring it when converting from the raw value to the decoded field value.

```
Currently on line 543 in messages.py:

       return math.copysign((round(turn / 4.733)) ** 2, turn)

Should it be?
       return math.copysign((round(turn / 4.733) ** 2), turn)
```
Thanks.

**Comment by M0r13n** [comment]
Hey @bgercken,

a lot going on here. I try to answer your questions 1 by 1 :-D.

> I am seeing a lot of sentences where the value for "turn" is being set to None

This is intentional. [Turn rate is encoded as follows ](https://gpsd.gitlab.io/gpsd/AIVDM.html#_types_1_2_and_3_position_report_class_a):

- 0 = not turning
- 1…​126 = turning right at up to 708 degrees per minute or higher
- 1…​-126 = turning left at up to 708 degrees per minute or higher
- 127 = turning right at more than 5deg/30s (No TI available)
- 127 = turning left at more than 5deg/30s (No TI available)
- 128 (80 hex) indicates no turn information available (default)

If no turn information is available the `turn` field is set to `None`.

> Now I have a new question to consider. It appears that you may be rounding the product before squaring it when converting from the raw value to the decoded field value.

I think you are right. The GPSD project - the de facto reference documentation for this project - does not even round: https://gitlab.com/gpsd/gpsd/-/blob/master/devtools/ais.py#L117. So I dropped the `round` statement and it seems to work correctly. 

However, I am not 100% sure, since the values for ROT vary slightly from decoder to decoder. Depending on the decoder, there seems to be a certain confidence interval of +/- 5 degrees, in which all available decoders scatter. :shrug:

Anyways, thank your the tip.

**Comment by M0r13n** [comment]
Closed by https://github.com/M0r13n/pyais/pull/74/files
