### ISSUE TITLE
Message decoding failed

### ISSUE THREAD

**Issue by cmslzs** [M0r13n/pyais#77]
![dcode_error](https://user-images.githubusercontent.com/49859201/183233759-d5c44e10-ddff-424f-98b2-eccca69f7e40.jpg)

**Comment by cmslzs** [comment]
Message decoding failed. Please check what is wrong, Thanks!

**Comment by M0r13n** [comment]
The error message is pretty clear. You passed a multi part message - several NMEA messages form a single AIS message - to the `decode` method. But you only passed the first part. Therefore, the message payload can not be decoded, because it missing parts of its content.

You can see this in the message itself. The message starts with `!AIVDM,2,1,1,B`, which means:

- `!AIVDM` identifies the message as an **AIVDM** message
- `2`: the current message as **two** fragments
- `1`: the current message is the **first** fragment (part) of a total of two fragments (parts)
- `1`: the sequential message ID is one (for multi sentence AIS messages)

As you can see, the full message consists of two individual fragments. Each fragment is a single NMEA sentence. Both fragments taken together contain the payload of the message. Each fragment on its own it worth nothing. Thus the `decode()` method expects all fragments.

**Comment by cmslzs** [comment]
a nmea message needs to have exactly 7 comma separated，
How do I need to correctly splice to analyze? Please tell me. I just got in touch with it and don't understand it
thanks
