### ISSUE TITLE
failed parse some MessageType5 data , it throw 'MissingMultipartMessageException'

### ISSUE THREAD

**Issue by icoco** [M0r13n/pyais#85]
face this problem, the  decode.py  code logic bellow:

  ```
 # Make sure provided parts assemble a single (multiline message)
    if len(args) > frag_cnt:
        raise TooManyMessagesException(f"Got {len(args)} messages, but fragment count is {frag_cnt}")

```
while parse string :  
!AIVDM,2,1,6,A,55MwgS`00001L@?;OK8<P58hE>0b0<Dp4>22220l1@:44vT4,0*6B

it throw exception:

```
 raise MissingMultipartMessageException(f"Missing fragment numbers: {diff}")
pyais.exceptions.MissingMultipartMessageException: Missing fragment numbers: [2]
```

what is the reason ?  

if I comment the check logic ,  then   all things works fine ,  anyone can give tip for this case ?

**Comment by mihermans** [comment]
Like the message indicates, it misses the second part of the multipart message. 
This message should start with !AIVDM,2,2,6..... in this case (the first digit indicates it is a multipart and the second digit if it is the first or second part of the message, the third digit indicates which messages belong together)

**Comment by icoco** [comment]
I use other way then no error report, the code below:
       ```
 data = b'!AIVDM,2,1,6,A,55MwgS`00001L@?;OK80b022220l1@:44vT4,0*6B'
        message = NMEAMessage(data) 
        decoded = message.decode()
```

@mihermans 
so, your meaning is the original data is wrong format ?

**Comment by M0r13n** [comment]
@mihermans is totally right. The error is pretty clear: You are trying to decode a multi fragment message. Such messages are too big to fit into the 82 character maximum of NMEA 0183 messages. Therefore, long messages are fragmented into multiple fragments. In order to decode a fragmented message, all fragments need to be assembled **before the message is decoded**. 

Imagine that you want to send a very big package to someone. Your package is too big to fit into a single parcel. Therefore, you split the package into multiple smaller packages. Each package can then be shipped in its own parcel. The receiver of the packages then needs to receive **all packages before he can reassemble the original package**. Otherwise the package would be incomplete. 
 
In your case the message `!AIVDM,2,1,6,A,55MwgS`00001L@?;OK80b022220l1@:44vT4,0*6B` starts with `!AIVDM,2,1`, which means that the message is fragmented into two (2) NMEA messages and you are trying to decode only the first (1) part of it. Instead you need to pass all parts to the `deode()` method.

> I use other way then no error report, the code below:

This may not raise an exception. But it is still wrong. The decoded message is **invalid**, because half of it is missing.

**Comment by icoco** [comment]
so then, how to solve this issue ?  sorry maybe my question is stupid  :-|

**Comment by M0r13n** [comment]
This is not an issue. This is expected behavior. You need to pass both parts the decode function - not just the first

**Comment by icoco** [comment]
got it...  thanks all
